name: Build TVBoxOS APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # 修复 gradlew 权限问题
    - name: Fix gradlew permissions
      run: |
        chmod +x gradlew
        ls -l gradlew

    # 安装 Python 3.8（Chaquopy 所需）
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    
    # 获取Python路径并设置为环境变量
    - name: Get Python path
      id: python-path
      run: |
        python_path=$(which python3)
        echo "PYTHON_PATH=$python_path" >> $GITHUB_ENV
        echo "Python path: $python_path"

    # 创建缺失的 local.properties 文件
    - name: Create local.properties
      run: |
        echo "sdk.dir=$ANDROID_HOME" > local.properties
        echo "ndk.dir=$ANDROID_HOME/ndk/25.1.8937393" >> local.properties
        cat local.properties

    # 设置 JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # 设置 Android SDK
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        packages: "platforms;android-33 build-tools;34.0.0 ndk;25.1.8937393 cmake;3.22.1"
        accept-android-sdk-licenses: true
        log-accepted-android-sdk-licenses: true

    # 修复项目结构并正确配置Chaquopy
    - name: Fix project structure and Chaquopy config
      run: |
        mkdir -p pyramid/build
        
        # 在 android 块内添加 Chaquopy 配置
        # 使用 sed 在 android { 后插入配置
        sed -i '/android {/a \
    defaultConfig { \
        python { \
            buildPython "'"$PYTHON_PATH"'" \
            pipOptions.extraIndexUrl "https://chaquo.com/pypi-7.0" \
        } \
    }' pyramid/build.gradle
        
        echo "org.gradle.caching=true" >> gradle.properties
        echo "org.gradle.parallel=true" >> gradle.properties
        echo "android.useAndroidX=true" >> gradle.properties
        
        # 验证修改
        echo "--- Modified pyramid/build.gradle ---"
        cat pyramid/build.gradle | grep -A 10 'android {'

    # 添加 Gradle 缓存
    - name: Cache Gradle dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          gradle-${{ runner.os }}-

    # 编译项目
    - name: Build APK
      run: |
        export GRADLE_OPTS="-Dorg.gradle.daemon=false"
        ./gradlew assembleDebug --stacktrace --info

    # 上传生成的 APK
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: TVBoxOS-APK
        path: app/build/outputs/apk/debug/*.apk