- name: Directly configure Chaquopy
  run: |
    # 在 android/defaultConfig 块内添加 Python 配置
    awk -v python_path="$PYTHON_PATH" '
    /android *{/ {
        print $0
        in_android = 1
        next
    }
    in_android && /defaultConfig *{/ {
        print $0
        print "            python {"
        print "                buildPython \"" python_path "\""
        print "                pipOptions.extraIndexUrl \"https://chaquo.com/pypi-7.0\""
        print "                staticProxy \"chaquopy.utils\""
        print "            }"
        print "            ndk {"
        print "                abiFilters \"armeabi-v7a\", \"arm64-v8a\", \"x86\", \"x86_64\""
        print "            }"
        next
    }
    /dependencies *{/ {
        print $0
        print "    implementation \"com.chaquo.python:gradle:12.0.0\""
        next
    }
    { print }' app/build.gradle > app/build.gradle.tmp
    
    mv app/build.gradle.tmp app/build.gradle
    
    # 修复关键版本设置
    sed -i 's/compileSdkVersion [0-9]*/compileSdkVersion 33/' app/build.gradle
    sed -i 's/buildToolsVersion .*/buildToolsVersion "34.0.0"/' app/build.gradle
    
    # 验证修改
    echo "===== app/build.gradle (android/defaultConfig block) ====="
    grep -A 20 'android *{' app/build.gradle
    echo "===== dependencies block ====="
    grep -A 5 'dependencies *{' app/build.gradle