name: Build TVBoxOS APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive  # 添加子模块初始化

    # 修复 gradlew 权限问题
    - name: Fix gradlew permissions
      run: |
        chmod +x gradlew
        ls -l gradlew

    # 安装 Python 3.8（Chaquopy 所需）
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    
    # 获取Python路径
    - name: Get Python path
      run: |
        python_path=$(which python3)
        echo "PYTHON_PATH=$python_path" >> $GITHUB_ENV

    # 创建缺失的 local.properties 文件
    - name: Create local.properties
      run: |
        echo "sdk.dir=$ANDROID_HOME" > local.properties
        echo "ndk.dir=$ANDROID_HOME/ndk/25.1.8937393" >> local.properties
        cat local.properties

    # 设置 JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # 设置 Android SDK
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        packages: |
          platforms;android-33 
          build-tools;34.0.0 
          ndk;25.1.8937393 
          cmake;3.22.1
        accept-android-sdk-licenses: true

    # 修复项目结构并正确配置Chaquopy
    - name: Configure Chaquopy
      run: |
        # 项目实际路径在app/目录下
        if [ -f app/build.gradle ]; then
          # 使用更可靠的awk添加配置
          awk -v python_path="$PYTHON_PATH" '
          /android *{/ {
            print $0
            print "    defaultConfig {"
            print "        python {"
            print "            buildPython \"" python_path "\""
            print "            pipOptions.extraIndexUrl \"https://chaquo.com/pypi-7.0\""
            print "        }"
            print "    }"
            next
          }
          { print }' app/build.gradle > app/build.gradle.tmp
          
          mv app/build.gradle.tmp app/build.gradle
          
          # 添加依赖到dependencies块
          sed -i '/dependencies *{/a \    implementation "com.chaquo.python:gradle:12.0.0"' app/build.gradle
          
          # 验证修改
          echo "--- Modified app/build.gradle ---"
          grep -A 10 'android *{' app/build.gradle
          grep -A 5 'dependencies *{' app/build.gradle
        else
          echo "ERROR: app/build.gradle not found!"
          exit 1
        fi

    # 添加 Gradle 缓存
    - name: Cache Gradle dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          gradle-${{ runner.os }}-

    # 编译项目
    - name: Build APK
      run: |
        export GRADLE_OPTS="-Dorg.gradle.daemon=false -Xmx4096m"
        ./gradlew :app:assembleDebug --stacktrace --info

    # 上传生成的 APK
    - name: Upload APK artifact
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: TVBoxOS-APK
        path: app/build/outputs/apk/debug/*.apk