name: Build TVBoxOS APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    # 1. 创建缺失的 local.properties 文件
    - name: Create local.properties
      run: |
        echo "sdk.dir=$ANDROID_HOME" > local.properties
        echo "Created local.properties"
        cat local.properties  # 验证文件内容
        
    # 2. 设置 JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    # 3. 设置 Android SDK (修复包格式)
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        # 关键修复：单行空格分隔格式
        packages: "platforms;android-33 build-tools;34.0.0 ndk;25.1.8937393 cmake;3.22.1"
        accept-android-sdk-licenses: true
        log-accepted-android-sdk-licenses: true
        
    # 4. 修复 TVBoxOS 项目结构
    - name: Fix project structure
      run: |
        # 创建 pyramid 模块需要的目录
        mkdir -p pyramid/build
        # 添加 Gradle 缓存优化
        echo "org.gradle.caching=true" >> gradle.properties
        echo "org.gradle.parallel=true" >> gradle.properties
        
    # 5. 添加 Gradle 缓存（加速后续构建）
    - name: Cache Gradle dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        
    # 6. 编译项目（带详细日志）
    - name: Build APK
      run: |
        ./gradlew assembleDebug --stacktrace --info
        
    # 7. 上传生成的 APK
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: TVBoxOS-APK
        path: app/build/outputs/apk/debug/*.apk