报错如下
> Configure project :app
Evaluating project ':app' using build file '/home/runner/work/tvbox/tvbox/app/build.gradle'.
Compiling build file '/home/runner/work/tvbox/tvbox/app/build.gradle' using SubsetScriptTransformer.

Compiling build file '/home/runner/work/tvbox/tvbox/app/build.gradle' using BuildScriptTransformer.
FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file '/home/runner/work/tvbox/tvbox/app/build.gradle' line: 3

* What went wrong:
A problem occurred evaluating project ':app'.
> No signature of method: build_a63r5e02ombh8gcezjugrh8ov.android() is applicable for argument types: (build_a63r5e02ombh8gcezjugrh8ov$_run_closure1) values: [build_a63r5e02ombh8gcezjugrh8ov$_run_closure1@5dd78e19]

* Try:
> Run with --debug option to get more log output.
> Run with --scan to get full insights.

* Exception is:
org.gradle.api.GradleScriptException: A problem occurred evaluating project ':app'.
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:93)
	
Caused by: groovy.lang.MissingMethodException: No signature of method: build_a63r5e02ombh8gcezjugrh8ov.android() is applicable for argument types: (build_a63r5e02ombh8gcezjugrh8ov$_run_closure1) values: [build_a63r5e02ombh8gcezjugrh8ov$_run_closure1@5dd78e19]
	at build_a63r5e02ombh8gcezjugrh8ov.run(/home/runner/work/tvbox/tvbox/app/build.gradle:3)
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:91)
	... 149 more

==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':app'.
> compileSdkVersion is not specified. Please add it to build.gradle

* Try:
> Run with --debug option to get more log output.
> Run with --scan to get full insights.

* Exception is:
org.gradle.api.ProjectConfigurationException: A problem occurred configuring project ':app'.
	at org.gradle.configuration.project.LifecycleProjectEvaluator.wrapException(LifecycleProjectEvaluator.java:75)
Caused by: com.android.builder.errors.EvalIssueException: compileSdkVersion is not specified. Please add it to build.gradle
	at com.android.builder.errors.IssueReporter.reportError(IssueReporter.kt:109)
	at java.base/java.lang.Thread.run(Thread.java:840)

==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 26s
Process completed with exit code 1.