name: Build TVBoxOS APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Fix gradlew permissions
      run: |
        chmod +x gradlew
        ls -l gradlew

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    
    - name: Get Python path
      run: |
        python_path=$(which python3)
        echo "PYTHON_PATH=$python_path" >> $GITHUB_ENV

    - name: Create local.properties
      run: |
        echo "sdk.dir=$ANDROID_HOME" > local.properties
        echo "ndk.dir=$ANDROID_HOME/ndk/25.1.8937393" >> local.properties
        cat local.properties

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        packages: |
          platforms;android-33 
          build-tools;34.0.0 
          ndk;25.1.8937393 
          cmake;3.22.1
        accept-android-sdk-licenses: true

    - name: Configure Chaquopy with minimal changes
      run: |
        # 备份原始文件
        cp app/build.gradle app/build.gradle.bak
        
        # 使用安全的插入方式 - 在android块内添加配置
        awk -v python_path="$PYTHON_PATH" '
        /android *{/ {
            print $0
            found_android = 1
            next
        }
        found_android && /defaultConfig *{/ {
            print $0
            print "            python {"
            print "                buildPython \"" python_path "\""
            print "                pipOptions.extraIndexUrl \"https://chaquo.com/pypi-7.0\""
            print "                staticProxy \"chaquopy.utils\""
            print "            }"
            print "            ndk {"
            print "                abiFilters \"armeabi-v7a\", \"arm64-v8a\", \"x86\", \"x86_64\""
            print "            }"
            next
        }
        { print }' app/build.gradle.bak > app/build.gradle
        
        # 添加依赖
        sed -i '/dependencies *{/a \    implementation "com.chaquo.python:gradle:12.0.0"' app/build.gradle
        
        # 修复关键版本设置
        sed -i 's/compileSdkVersion [0-9]*/compileSdkVersion 33/' app/build.gradle
        sed -i 's/buildToolsVersion .*/buildToolsVersion "34.0.0"/' app/build.gradle
        
        # 验证修改
        echo "===== Modified app/build.gradle ====="
        grep -A 15 'android *{' app/build.gradle
        echo "===== Dependencies ====="
        grep -A 5 'dependencies *{' app/build.gradle
        echo "===== Version Settings ====="
        grep -E 'compileSdkVersion|buildToolsVersion' app/build.gradle

    - name: Cache Gradle dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          gradle-${{ runner.os }}-

    - name: Build APK
      run: |
        export GRADLE_OPTS="-Dorg.gradle.daemon=false -Xmx4096m"
        ./gradlew clean :app:assembleDebug --stacktrace --info

    - name: Upload APK artifact
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: TVBoxOS-APK
        path: app/build/outputs/apk/debug/*.apk